//! Local round-trip verification.
//!
//! Every proof generated by this crate should be verified locally before it
//! is handed onward — a proof that does not verify against its own response
//! is a bug, not a deliverable. These helpers run that round-trip against any
//! registered [`Verifier`].

use crucible_interfaces::{ProofResponse, VerificationOutcome, VerificationRequest, Verifier};

use crate::errors::CoreError;

/// Verifies `response` with `verifier`, requiring a positive outcome.
///
/// Returns the outcome on success; a rejection is surfaced as
/// [`CoreError::NotVerified`] so callers cannot silently proceed with a proof
/// that failed its own round-trip.
pub fn verify_round_trip(
    verifier: &dyn Verifier,
    response: &ProofResponse,
) -> Result<VerificationOutcome, CoreError> {
    verify_round_trip_with(verifier, VerificationRequest::from_response(response))
}

/// Verifies an explicit request (useful for tamper/stale-state checks where
/// the request differs from the response).
pub fn verify_round_trip_with(
    verifier: &dyn Verifier,
    request: VerificationRequest,
) -> Result<VerificationOutcome, CoreError> {
    let outcome = verifier
        .verify(&request)
        .map_err(|e| CoreError::Internal(e.to_string()))?;
    if !outcome.verified {
        return Err(CoreError::NotVerified(outcome.failure));
    }
    Ok(outcome)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crucible_interfaces::ProofProvider;
    use crucible_mock::{MockProver, MockVerifier, fixtures};

    #[test]
    fn fresh_proof_passes_its_own_round_trip() {
        let request = fixtures::transfer_request();
        let response = MockProver::new().generate(&request).unwrap();
        let outcome = verify_round_trip(&MockVerifier::new(), &response).unwrap();
        assert!(outcome.verified);
    }

    #[test]
    fn mismatched_verifier_rejects_as_error() {
        let request = fixtures::transfer_request();
        let response = MockProver::new().generate(&request).unwrap();
        // A verifier with a different key must not verify the proof.
        let err = verify_round_trip(&MockVerifier::with_key("other"), &response).unwrap_err();
        assert!(matches!(err, CoreError::NotVerified(_)));
    }
}
