//! Live UltraHonk proving and verification through the real Barretenberg
//! backend.
//!
//! Everything in this file exercises **real cryptography**: witnesses solved
//! by `nargo` from committed vector fixtures, proofs generated by `bb` with
//! the `ultra_honk` scheme, and verification by `bb verify`. The mock tier
//! is deliberately absent — these tests exist because the mock cannot judge
//! cryptographic soundness, and they are gated on both `nargo` and `bb`
//! being on `PATH`.
//!
//! Each test runs a fresh `bb prove`, so the suite is slow by design and
//! lives in the CI circuits job where the toolchain pair is installed and
//! pinned.

use std::path::{Path, PathBuf};

use crucible_noir::NoirToolchain;
use crucible_tests::circuit_runner::{CircuitScratch, write_prover_toml};
use crucible_tests::vectors::{TestVector, load_catalog};
use crucible_ultrahonk::{
    BbToolchain, ProveOptions, SCHEME_ULTRA_HONK, TESTED_BB_VERSION, VerifyOptions, prove,
    verify,
};

/// Loads one vector from the committed catalog by id.
fn vector(id: &str) -> TestVector {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../test-vectors");
    load_catalog(&root)
        .expect("catalog must load")
        .into_iter()
        .find(|v| v.id == id)
        .unwrap_or_else(|| panic!("vector `{id}` must exist in the catalog"))
}

/// Both toolchains must be present for live proving; otherwise the tests
/// skip (they are wired into CI jobs that install and pin the pair).
fn toolchains() -> Option<(NoirToolchain, BbToolchain)> {
    if !NoirToolchain::is_available() || !BbToolchain::is_available() {
        eprintln!("skipping: nargo and bb must both be on PATH for live proving");
        return None;
    }
    Some((
        NoirToolchain::locate().expect("nargo available"),
        BbToolchain::locate().expect("bb available"),
    ))
}

/// A witness solved from a vector, plus the bytecode to prove it against.
///
/// Holds the scratch [`CircuitScratch`] so the temp package (and its solved
/// witness and compiled artifact) outlives this struct.
struct Solved {
    /// Scratch package holding bytecode + witness.
    #[allow(dead_code)]
    scratch: CircuitScratch,
    /// Compiled ACIR bytecode (`<scratch>/<op>/target/<op>.json`).
    bytecode: PathBuf,
    /// Solved witness (`target/<name>.gz`).
    witness: PathBuf,
}

/// Solves a vector's witness against the real circuit package `op`.
fn solve(op: &str, vector: &TestVector, toolchain: &NoirToolchain) -> Solved {
    let scratch = CircuitScratch::prepare(op).expect("scratch package prepared");
    write_prover_toml(&scratch, vector).expect("Prover.toml written");
    let captured = scratch.execute(toolchain).expect("nargo execute ran");
    assert!(
        captured.solved,
        "valid vector must solve the {op} circuit: {}",
        captured.exit_code.map(|c| c.to_string()).unwrap_or_default()
    );
    let witness = captured.witness_path.expect("solved witness written");
    let bytecode = scratch.package_dir.join("target").join(format!("{op}.json"));
    assert!(
        bytecode.is_file(),
        "compiled bytecode must exist at {}",
        bytecode.display()
    );
    Solved {
        scratch,
        bytecode,
        witness,
    }
}

/// Canonical form for comparing `0x`-padded backend words with canonical
/// (no-leading-zero) fixture hex.
fn canonical(hex: &str) -> String {
    let bare = hex.strip_prefix("0x").unwrap_or(hex);
    let trimmed = bare.trim_start_matches('0');
    if trimmed.is_empty() {
        "0".to_owned()
    } else {
        trimmed.to_ascii_lowercase()
    }
}

/// Flips one hex nibble of a `0x`-prefixed word while keeping it valid hex
/// and the same length.
fn flip_word(word: &str) -> String {
    let mut chars: Vec<char> = word.chars().collect();
    let i = if chars.get(0..2) == Some(&['0', 'x']) { 2 } else { 0 };
    chars[i] = if chars[i] == '0' { '1' } else { '0' };
    chars.into_iter().collect()
}

/// Proves `solved` into a fresh temp dir and returns the parsed artifacts
/// and the artifact file paths.
fn prove_bundle(
    bb: &BbToolchain,
    solved: &Solved,
) -> (crucible_ultrahonk::ProvenArtifacts, tempfile::TempDir) {
    let dir = tempfile::tempdir().expect("temp dir");
    let artifacts = prove(
        bb,
        &ProveOptions {
            bytecode: &solved.bytecode,
            witness: &solved.witness,
            output_dir: dir.path(),
            write_vk: true,
        },
    )
    .expect("bb prove must succeed on a solved witness");
    (artifacts, dir)
}

#[test]
fn register_proof_round_trips_and_binds_the_public_address() {
    let Some((nargo, bb)) = toolchains() else {
        return;
    };
    let vector = vector("register-valid-001");
    let solved = solve("register", &vector, &nargo);

    let (artifacts, _dir) = prove_bundle(&bb, &solved);

    // Provenance: bb stamps scheme + version into every artifact.
    assert_eq!(artifacts.proof.scheme, SCHEME_ULTRA_HONK);
    assert_eq!(artifacts.proof.bb_version, TESTED_BB_VERSION);
    assert_eq!(artifacts.proof.vk_hash_bytes().unwrap().len(), 32);
    let vk = artifacts.vk.as_ref().expect("write_vk requested");
    assert_eq!(vk.hash_bytes().unwrap(), artifacts.proof.vk_hash_bytes().unwrap());

    // Register exposes exactly one public input: the account address. The
    // proof must bind to it — this is the crypto-level ownership statement.
    assert_eq!(artifacts.public_inputs.public_inputs.len(), 1);
    let expected = vector
        .witness
        .public
        .get("account_address")
        .expect("register vector carries account_address");
    assert_eq!(
        canonical(&artifacts.public_inputs.public_inputs[0]),
        canonical(expected.as_hex()),
        "the proof's public input must equal the account address"
    );

    // And the proof verifies against the produced bundle.
    let files = artifacts.files();
    let outcome = verify(
        &bb,
        &VerifyOptions {
            proof: &files.proof,
            vk: &files.vk.expect("vk written"),
            public_inputs: &files.public_inputs,
        },
    )
    .expect("bb verify must run");
    assert!(outcome.verified, "fresh UltraHonk proof must verify");
}

#[test]
fn tampered_proof_is_rejected_by_the_ultra_honk_verifier() {
    let Some((nargo, bb)) = toolchains() else {
        return;
    };
    let vector = vector("register-valid-001");
    let solved = solve("register", &vector, &nargo);
    let (artifacts, _dir) = prove_bundle(&bb, &solved);
    let files = artifacts.files();

    // Tamper one proof word in a copy, keep vk + public inputs pristine.
    let tamper_dir = tempfile::tempdir().expect("temp dir");
    let tampered_proof = tamper_dir.path().join("proof.json");
    let doc: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&files.proof).unwrap()).unwrap();
    let idx = doc["proof"].as_array().unwrap().len() / 2;
    let word = doc["proof"][idx].as_str().unwrap().to_owned();
    let mut tampered = doc;
    tampered["proof"][idx] = serde_json::Value::String(flip_word(&word));
    std::fs::write(&tampered_proof, serde_json::to_string(&tampered).unwrap()).unwrap();

    let outcome = verify(
        &bb,
        &VerifyOptions {
            proof: &tampered_proof,
            vk: &files.vk.expect("vk written"),
            public_inputs: &files.public_inputs,
        },
    )
    .expect("bb verify must run");
    assert!(!outcome.verified, "a tampered proof must be rejected");
    let diagnostic = outcome.diagnostic.as_deref().unwrap_or_default();
    assert!(
        !diagnostic.is_empty(),
        "a rejected proof should carry a diagnostic"
    );
}

#[test]
fn wrong_verification_key_is_rejected() {
    let Some((nargo, bb)) = toolchains() else {
        return;
    };
    let vector = vector("register-valid-001");
    let solved = solve("register", &vector, &nargo);
    let (artifacts, _dir) = prove_bundle(&bb, &solved);
    let files = artifacts.files();

    // A proof must verify only under its own verification key: tamper one
    // VK word (a different circuit's VK is indistinguishable from a tampered
    // one at the byte level, and must fail the same way).
    let tamper_dir = tempfile::tempdir().expect("temp dir");
    let tampered_vk = tamper_dir.path().join("vk.json");
    let doc: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(files.vk.as_ref().unwrap()).unwrap())
            .unwrap();
    let idx = doc["vk"].as_array().unwrap().len() / 2;
    let word = doc["vk"][idx].as_str().unwrap().to_owned();
    let mut tampered = doc;
    tampered["vk"][idx] = serde_json::Value::String(flip_word(&word));
    std::fs::write(&tampered_vk, serde_json::to_string(&tampered).unwrap()).unwrap();

    let outcome = verify(
        &bb,
        &VerifyOptions {
            proof: &files.proof,
            vk: &tampered_vk,
            public_inputs: &files.public_inputs,
        },
    )
    .expect("bb verify must run");
    assert!(!outcome.verified, "a proof under the wrong VK must be rejected");
}

#[test]
fn public_input_mismatch_is_rejected() {
    let Some((nargo, bb)) = toolchains() else {
        return;
    };
    let vector = vector("register-valid-001");
    let solved = solve("register", &vector, &nargo);
    let (artifacts, _dir) = prove_bundle(&bb, &solved);
    let files = artifacts.files();

    // The proof commits to its public inputs: submit it against a *changed*
    // account address and it must fail — this is the crypto-level version of
    // the stale-state / wrong-context rejection the mock only simulates.
    let tamper_dir = tempfile::tempdir().expect("temp dir");
    let tampered_pi = tamper_dir.path().join("public_inputs.json");
    let doc: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&files.public_inputs).unwrap()).unwrap();
    let word = doc["public_inputs"][0].as_str().unwrap().to_owned();
    let mut tampered = doc;
    tampered["public_inputs"][0] = serde_json::Value::String(flip_word(&word));
    std::fs::write(&tampered_pi, serde_json::to_string(&tampered).unwrap()).unwrap();

    let outcome = verify(
        &bb,
        &VerifyOptions {
            proof: &files.proof,
            vk: &files.vk.expect("vk written"),
            public_inputs: &tampered_pi,
        },
    )
    .expect("bb verify must run");
    assert!(
        !outcome.verified,
        "a proof submitted against different public inputs must be rejected"
    );
}

#[test]
fn transfer_proof_binds_token_address_and_reports_outputs() {
    let Some((nargo, bb)) = toolchains() else {
        return;
    };
    let vector = vector("transfer-valid-001");
    let solved = solve("transfer", &vector, &nargo);
    let (artifacts, _dir) = prove_bundle(&bb, &solved);

    // transfer's public surface: 6 public params (token, sender, recipient,
    // old commitment, root_hi, root_lo) followed by the 3 returned
    // commitments/nullifier — 9 words total.
    let words = &artifacts.public_inputs.public_inputs;
    assert_eq!(words.len(), 9, "transfer exposes 9 public input words");

    let token = vector
        .witness
        .public
        .get("token_address")
        .expect("transfer vector carries token_address");
    assert_eq!(
        canonical(&words[0]),
        canonical(token.as_hex()),
        "first public input is the token address"
    );

    // Words 4 and 5 are the state-root halves the circuit commits to; the
    // fixture's state root split in half must match them exactly.
    let state = vector.state_reference.as_ref().expect("transfer is state-bound");
    let (hi, lo) = state.root_halves();
    assert_eq!(canonical(&words[4]), canonical(hi.as_hex()));
    assert_eq!(canonical(&words[5]), canonical(lo.as_hex()));

    // The final three words are the return tuple in order: recipient
    // commitment, change commitment, nullifier.
    let expected: Vec<String> = vector
        .expected_public_outputs
        .iter()
        .map(|(name, value)| format!("{name}={}", value.as_hex()))
        .collect();
    assert_eq!(expected.len(), 3, "transfer returns three outputs");
    for (i, (name, value)) in vector.expected_public_outputs.iter().enumerate() {
        assert_eq!(
            canonical(&words[6 + i]),
            canonical(value.as_hex()),
            "public input word {} must be the `{name}` output",
            6 + i
        );
    }

    let files = artifacts.files();
    let outcome = verify(
        &bb,
        &VerifyOptions {
            proof: &files.proof,
            vk: &files.vk.expect("vk written"),
            public_inputs: &files.public_inputs,
        },
    )
    .expect("bb verify must run");
    assert!(outcome.verified, "fresh transfer UltraHonk proof must verify");
}
