//! UltraHonk backend identity and version compatibility.
//!
//! Proofs are only reproducible when the exact backend version that produced
//! them is known: an UltraHonk proof generated by one Barretenberg version
//! may not verify with another. This module pins the backend identity and
//! declares which versions of the toolchain components Crucible knows to be
//! mutually compatible.

use crucible_interfaces::{BackendId, CircuitId, Operation, Version};

use crate::errors::UltraHonkError;
use crate::TESTED_BB_VERSION;

/// The backend id used on the wire and in providers.
pub const BACKEND_ID: &str = "ultrahonk";

/// One row of the compatibility matrix: which `(nargo, bb)` versions this
/// crate was validated against for a given operation set.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CompatEntry {
    /// Nargo (compiler) version.
    pub nargo: &'static str,
    /// Barretenberg (prover/verifier) version.
    pub bb: &'static str,
    /// Circuit versions proven with this toolchain pair.
    pub circuits: Version,
}

/// Backends known to this crate, with their compatibility matrix.
///
/// This is a *knowledge base*, seeded from the toolchain this repository is
/// developed against. The single entry below is the pairing the Barretenberg
/// adapter is **validated against** in CI: circuits compiled with this nargo
/// release prove and verify with this bb release (scheme `ultra_honk`).
pub const BACKEND_COMPAT: &[CompatEntry] = &[CompatEntry {
    nargo: "1.0.0-beta.26",
    bb: TESTED_BB_VERSION,
    circuits: Version::new(0, 1, 0),
}];

/// Marker type implementing the backend-identity contract.
#[derive(Debug, Clone, Copy, Default)]
pub struct UltraHonkBackend;

impl UltraHonkBackend {
    /// The canonical backend id.
    pub fn id() -> BackendId {
        BackendId::new(BACKEND_ID).expect("ultrahonk backend id is valid")
    }

    /// Whether this backend is compatible with `circuit` at `version`.
    ///
    /// The five protocol circuits are the supported surface; custom circuits
    /// are supported only once a compat entry exists for them.
    pub fn supports(circuit: &CircuitId, version: &Version) -> bool {
        if !Self::is_protocol_circuit(circuit) {
            return false;
        }
        BACKEND_COMPAT
            .iter()
            .any(|entry| entry.circuits == *version)
    }

    fn is_protocol_circuit(circuit: &CircuitId) -> bool {
        [
            Operation::Register,
            Operation::Deposit,
            Operation::Merge,
            Operation::Transfer,
            Operation::Withdraw,
        ]
        .iter()
        .any(|op| CircuitId::for_operation(*op) == *circuit)
    }

    /// Validates that a requested `(circuit, version)` is supported,
    /// returning a structured error otherwise.
    pub fn check_supported(circuit: &CircuitId, version: &Version) -> Result<(), UltraHonkError> {
        if Self::supports(circuit, version) {
            return Ok(());
        }
        let supported = BACKEND_COMPAT
            .iter()
            .map(|e| e.circuits.to_string())
            .collect::<Vec<_>>()
            .join(", ");
        Err(UltraHonkError::UnsupportedVersion {
            backend: BACKEND_ID.to_owned(),
            version: version.to_string(),
            supported,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn backend_id_is_stable() {
        assert_eq!(UltraHonkBackend::id().as_str(), BACKEND_ID);
    }

    #[test]
    fn protocol_circuits_at_current_version_are_supported() {
        for op in [
            Operation::Register,
            Operation::Deposit,
            Operation::Merge,
            Operation::Transfer,
            Operation::Withdraw,
        ] {
            let circuit = CircuitId::for_operation(op);
            assert!(UltraHonkBackend::supports(&circuit, &Version::new(0, 1, 0)));
            assert!(UltraHonkBackend::check_supported(&circuit, &Version::new(0, 1, 0)).is_ok());
        }
    }

    #[test]
    fn unknown_circuit_or_version_is_rejected() {
        let circuit = CircuitId::new("custom").unwrap();
        assert!(!UltraHonkBackend::supports(
            &circuit,
            &Version::new(0, 1, 0)
        ));
        assert!(UltraHonkBackend::check_supported(&circuit, &Version::new(0, 1, 0)).is_err());

        let circuit = CircuitId::for_operation(Operation::Transfer);
        assert!(!UltraHonkBackend::supports(
            &circuit,
            &Version::new(9, 0, 0)
        ));
        assert!(UltraHonkBackend::check_supported(&circuit, &Version::new(9, 0, 0)).is_err());
    }

    #[test]
    fn compat_matrix_is_consistent() {
        assert!(!BACKEND_COMPAT.is_empty());
        for entry in BACKEND_COMPAT {
            assert!(!entry.nargo.is_empty());
            assert!(!entry.bb.is_empty());
        }
    }
}
