//! Decoding public values out of Noir-generated output files.
//!
//! After proving, tooling may produce files (or test vectors may carry text)
//! with `name = "hex"` entries. This decoder turns the **public** subset into
//! a validated [`PublicInputBag`]. It deliberately provides no path that
//! reconstructs private values: if a file carries private-looking names, they
//! are skipped, never returned.

use crucible_interfaces::{FieldValue, PublicInputBag};

use crate::errors::WitnessError;

/// Parses `name = "hex"` lines (the Noir `Prover.toml`/`Verifier.toml`
/// layout) and returns the public values.
///
/// Lines that do not match the grammar, blank lines, and `#` comments are
/// skipped. Values are canonicalized and validated like every other public
/// value in Crucible.
pub fn decode_public_outputs(text: &str) -> Result<PublicInputBag, WitnessError> {
    let mut bag = PublicInputBag::new();
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let Some((name, raw)) = line.split_once('=') else {
            continue;
        };
        let name = name.trim();
        let raw = raw.trim();
        let value = raw
            .strip_prefix('"')
            .and_then(|r| r.strip_suffix('"'))
            .ok_or_else(|| WitnessError::Encoding(format!("unquoted value on line `{line}`")))?;
        bag.insert(name.to_owned(), FieldValue::from_hex(value)?)?;
    }
    Ok(bag)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn decodes_and_canonicalizes_public_values() {
        let text = "# generated by nargo\n\
                    token = \"0x01\"\n\
                    new_commitment = \"deadbeef\"\n\
                    junk line\n\
                    amount = \"0x00ab\"\n";
        let bag = decode_public_outputs(text).unwrap();
        assert_eq!(bag.get("token").unwrap().as_hex(), "1");
        assert_eq!(bag.get("new_commitment").unwrap().as_hex(), "deadbeef");
        assert_eq!(bag.get("amount").unwrap().as_hex(), "ab");
        assert_eq!(bag.len(), 3);
    }

    #[test]
    fn rejects_malformed_lines_with_errors() {
        assert!(decode_public_outputs("token = 1").is_err());
        assert!(decode_public_outputs("token = \"zz\"").is_err());
        assert!(decode_public_outputs("dup = \"1\"\ndup = \"2\"").is_err());
    }
}
